algoritmo "numeroParOuImpar"
// Função : crie um programa que solicite um número ao usuário e informe se é par ou impar
// Autor : grupo 1
// Data : 16/04/2024

var
numero : inteiro
inicio
ESCREVA("Digite um número para verifica se é par ou impar : ")
LEIA(numero)
ESCREVAL("")
SE numero MOD 2 = 0 ENTAO
       ESCREVAL("O número digita é ", numero, " este número é par !")
SENAO
       ESCREVAL("O numero digitado é ", numero, " este número é impar !")

FIMSE


fimalgoritmo
