Algoritmo "para"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Rosanete Grassiani dos Santos
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 15/04/2024
Var
// Seção de Declarações das variáveis
  contador: inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc...
   para contador <- 1 ate 5 faca
   escreval (contador)
   fimpara

Fimalgoritmo